---

- name: Install mariadb package
  package:
    name: mariadb-server
    state: latest

- name: Enable mariadb service
  service:
    name: mariadb
    enabled: yes

- name: Start MariaDB service
  service:
    name: mysql
    state: started
    enabled: yes
