---

- name: Install mariadb package
  package:
    name: mariadb-server
    state: latest

- name: Enable mariadb service
  service:
    name: mariadb
    enabled: yes


- name: Install PyMySQL python package (dependency for ansible mysql modules)
  package:
    name: python2-PyMySQL
    state: latest
