---

- name: Install OpenJDK
  package:
    name: java-1.8.0-openjdk
    state: latest

- name: Install unzip package
  package:
    name: unzip
    state: latest

# Reuse downloaded zip instead of downloading it on every run. (Only useful for development)
- stat:
    path: /tmp/glassfish4.zip
  register: glassfish_zip

- name: Download glassfish zip archive
  get_url:
    # Saddly the glassfish developers don' provide checksums for their zips
    url: https://download.oracle.com/glassfish/4.1/release/glassfish-4.1.zip
    dest: /tmp/glassfish4.zip
  when: not glassfish_zip.stat.exists

- name: Unzip glassfish archive
  unarchive:
    remote_src: yes
    src: /tmp/glassfish4.zip
    dest: /opt/

- name: Copy systemd unit file
  copy:
    src: glassfish.service
    dest: /lib/systemd/system/glassfish.service
