---

- name: Install OpenJDK
  package:
    name: java-1.8.0-openjdk
    state: latest

- name: Install unzip package
  package:
    name: unzip
    state: latest

- name: Download glassfish zip archive
  get_url:
    url: "{{glassfish4_download_url}}"
    dest: "/tmp/{{glassfish4_zip_name}}"
    checksum: "{{glassfish4_zip_checksum}}"

- name: Unzip glassfish archive
  unarchive:
    remote_src: yes
    src: "/tmp/{{glassfish4_zip_name}}"
    dest: /opt/

- name: Download mysql java connector tarball archive
  get_url:
    url: "{{glassfish4_mysql_java_connector_download_url}}"
    dest: "/tmp/{{glassfish4_mysql_java_connector_tarball_name}}"
    checksum: "{{glassfish4_mysql_java_connector_tarball_checksum}}"

- name: Unzip glassfish archive
  unarchive:
    remote_src: yes
    src: "/tmp/{{glassfish4_mysql_java_connector_tarball_name}}"
    dest: /opt/

- name: Copy mysql java connector to glassfish library directory
  copy:
    src: "/opt/mysql-connector-java-5.1.47/mysql-connector-java-5.1.47-bin.jar"
    dest: "/opt/glassfish4/glassfish/domains/domain1/lib/ext/"
    remote_src: yes

- name: Copy systemd unit file
  copy:
    src: glassfish.service
    dest: /lib/systemd/system/glassfish.service
