---

# Name of of the mysql java connector tarball
specchio_webapp_glassfish_mysql_java_connector_tarball_name: "mysql-connector-java-5.1.47.tar.gz"

# Download link of mysql java connector
specchio_webapp_glassfish_mysql_java_connector_download_url: "http://cdn.mysql.com/Downloads/Connector-J/{{specchio_webapp_glassfish_mysql_java_connector_tarball_name}}"

# Checksum of the mysql java connector tarball
specchio_webapp_glassfish_mysql_java_connector_tarball_checksum: "sha256:4ae79214b2f1b5fc600fc867a4d27dcfcb467813c38bf3eee87789ba400349c6"

# Name of the glassfish zip
specchio_webapp_glassfish_zip_name: "glassfish-4.1.zip"

# Download link of glassfish
specchio_webapp_glassfish_download_url: "https://download.oracle.com/glassfish/4.1/release/{{specchio_webapp_glassfish_zip_name}}"

# Directory of the glassfish application server
specchio_webapp_glassfish_directory: "/opt/glassfish4"

# Asadmin file to interact with glassfish
specchio_webapp_glassfish_asadmin_file: "{{ specchio_webapp_glassfish_directory }}/glassfish/bin/asadmin"

# Directory of the glassfish specchio domain
specchio_webapp_glassfish_domain_directory: "{{ specchio_webapp_glassfish_directory }}/glassfish/domains/domain1/"

# Directory for domain external libraries
specchio_webapp_glassfish_domain_external_libraries_directory: "{{ specchio_webapp_glassfish_domain_directory }}/lib/ext/"

# Path to the glassfish domain configuration file
specchio_webapp_glassfish_domain_configuration_file: "{{ specchio_webapp_glassfish_domain_directory }}/config/domain.xml"

# Path to the glassfish unit file
specchio_webapp_glassfish_systemd_unit_file: "/lib/systemd/system/glassfish.service"

# Checksum of the glassfish zip
specchio_webapp_glassfish_zip_checksum: "sha256:3edc5fc72b8be241a53eae83c22f274479d70e15bdfba7ba2302da5260f23e9d"

# Download url for the specchio-webapp.war
specchio_webapp_download_url: "https://github.com/ahueni/SPECCHIO/raw/SPECCHIO_Master/pkg/specchio-webapp.war"

# Directory where to place the webapp
specchio_webapp_directory: "/opt/specchio_webapp/"

# Path to webapp war
specchio_webapp_war: "{{ specchio_webapp_directory }}/specchio-webapp.war"

# Name of the JDBC connectin pool
specchio_webapp_glassfish_jdbc_connection_pool_name: "specchio_web_pool"

# JNDI name
specchio_webapp_glassfish_jndi_name: "jdbc/specchio"

# Glassfish security realm settings
specchio_webapp_glassfish_security_realm_name: "jdbcRealm"
specchio_webapp_glassfish_security_realm_hash_function: "MD5"
specchio_webapp_glassfish_security_realm_group_table: "specchio.specchio_user_group"
specchio_webapp_glassfish_security_realm_group_name_column: "group_name"
specchio_webapp_glassfish_security_realm_group_table_user_name_column: "user"
specchio_webapp_glassfish_security_realm_user_table: "specchio.specchio_user"
specchio_webapp_glassfish_security_realm_password_column: "password"
specchio_webapp_glassfish_security_realm_user_name_column: "user"

# Database connection information
specchio_webapp_database_port: "3306"
specchio_webapp_database_host: "localhost"
specchio_webapp_database_name: "specchio"
specchio_webapp_database_user: "sdb_admin"
specchio_webapp_database_password: "ALSOCHANGEME"
