---

# Name of of the mysql java connector tarball
specchio_webapp_glassfish_mysql_java_connector_tarball_name: "mysql-connector-java-5.1.47.tar.gz"

# Download link of mysql java connector
specchio_webapp_glassfish_mysql_java_connector_download_url: "http://cdn.mysql.com/Downloads/Connector-J/{{specchio_webapp_glassfish_mysql_java_connector_tarball_name}}"

# Checksum of the mysql java connector tarball
specchio_webapp_glassfish_mysql_java_connector_tarball_checksum: "sha256:4ae79214b2f1b5fc600fc867a4d27dcfcb467813c38bf3eee87789ba400349c6"

# Name of the glassfish zip
specchio_webapp_glassfish_zip_name: "glassfish-4.1.zip"

# Download link of glassfish
specchio_webapp_glassfish_download_url: "https://download.oracle.com/glassfish/4.1/release/{{specchio_webapp_glassfish_zip_name}}"

# Directory of the glassfish application server
specchio_webapp_glassfish_directory: "/opt/glassfish4"

# Asadmin file to interact with glassfish
specchio_webapp_glassfish_asadmin_file: "{{ specchio_webapp_glassfish_directory }}/glassfish/bin/asadmin"

# Directory of the glassfish specchio domain
specchio_webapp_glassfish_domain_directory: "{{ specchio_webapp_glassfish_directory }}/glassfish/domains/domain1/"

# Directory for domain external libraries
specchio_webapp_glassfish_domain_external_libraries_directory: "{{ specchio_webapp_glassfish_domain_directory }}/lib/ext/"

# Path to the glassfish domain configuration directory
specchio_webapp_glassfish_domain_configuration_directory: "{{ specchio_webapp_glassfish_domain_directory }}/config/"

# Path to the glassfish domain configuration file
specchio_webapp_glassfish_domain_configuration_file: "{{ specchio_webapp_glassfish_domain_configuration_directory }}/domain.xml"

# Path to the glassfish unit file
specchio_webapp_glassfish_systemd_unit_file: "/lib/systemd/system/glassfish.service"

# Checksum of the glassfish zip
specchio_webapp_glassfish_zip_checksum: "sha256:3edc5fc72b8be241a53eae83c22f274479d70e15bdfba7ba2302da5260f23e9d"

# Download url for the specchio-webapp.war
specchio_webapp_download_url: "https://jenkins.winpat.ch/job/SPECCHIO/lastSuccessfulBuild/artifact/src/webapp/build/distributions/specchio-webapp.zip"

# Where to extract the zip archive
specchio_webapp_extraction_directory: "/opt/SPECCHIO"

# Directory where extracted webapp is stored
specchio_webapp_directory: "{{ specchio_webapp_extraction_directory }}/specchio-webapp"

specchio_webapp_sql_directory: "{{ specchio_webapp_directory }}/mysql"

# Path to webapp war
specchio_webapp_war: "{{ specchio_webapp_directory }}/webapp-3.3.0.war"

# Name of the JDBC connectin pool
specchio_webapp_glassfish_jdbc_connection_pool_name: "specchio_web_pool"

# JNDI name
specchio_webapp_glassfish_jndi_name: "jdbc/specchio"

# Glassfish security realm settings
specchio_webapp_glassfish_security_realm_name: "specchioRealm"
specchio_webapp_glassfish_security_realm_hash_function: "MD5"
specchio_webapp_glassfish_security_realm_group_table: "specchio.specchio_user_group"
specchio_webapp_glassfish_security_realm_group_name_column: "group_name"
specchio_webapp_glassfish_security_realm_group_table_user_name_column: "user"
specchio_webapp_glassfish_security_realm_user_table: "specchio.specchio_user"
specchio_webapp_glassfish_security_realm_password_column: "password"
specchio_webapp_glassfish_security_realm_user_name_column: "user"

# Database connection information
specchio_webapp_database_install: true
specchio_webapp_database_port: "3306"
specchio_webapp_database_host: "localhost"
specchio_webapp_database_name: "specchio"
specchio_webapp_database_user: "sdb_admin"
specchio_webapp_database_password: "ALSOCHANGEME"

# Password of the glassfish domain keystore
specchio_webapp_keystore_file: "{{ specchio_webapp_glassfish_domain_configuration_directory }}/keystore.jks"
specchio_webapp_keystore_keypass: "changeit"
specchio_webapp_keystore_storepass: "changeit"
specchio_webapp_keystore_alias: "specchio_trust"

# Path and password of the cacerts keystore
specchio_webapp_cacerts_file: "{{ specchio_webapp_glassfish_domain_configuration_directory }}/cacerts.jks"
specchio_webapp_cacerts_storepass: "changeit"

# Location of where the server certificate and csr will stored outside the keystore (as copies)
specchio_webapp_server_csr_file: "{{ specchio_webapp_glassfish_directory }}/specchio_server.csr"
specchio_webapp_server_crt_file: "{{ specchio_webapp_glassfish_directory }}/specchio_server.crt"
specchio_webapp_server_crt_alias: "s1as"

# Path where the SPECCHIO CA cert will be stored
specchio_webapp_ca_crt_file: "{{ specchio_webapp_glassfish_directory }}/specchio_ca.crt"
specchio_webapp_ca_crt_alias: "specchio_trust"

# Path where the SPECCHIO CA PKCS12 (incl. private key) will be stored
specchio_webapp_ca_pkcs12_keystore_file: "{{ specchio_webapp_glassfish_directory }}/specchio_ca.p12"
specchio_webapp_ca_pkcs12_keystore_password: "changeit"
specchio_webapp_ca_pkcs12_keystore_alias: "specchio_trust"
