---

- name: Install OpenJDK
  package:
    name: java-1.8.0-openjdk
    state: latest

- name: Install unzip
  package:
    name: unzip
    state: latest

- name: Create SPECCHIO client extraction directory
  file:
    path: "{{ specchio_client_extraction_directory }}"
    state: directory

- name: Download SPECCHIO client zip
  unarchive:
    src: "{{ specchio_client_download_url }}"
    dest: "{{ specchio_client_extraction_directory }}"
    remote_src: yes

- name: Copy SPECCHIO CA certificate
  copy:
    src: specchio_ca.crt
    dest: "{{ specchio_client_ca_crt_file }}"

- name: Add SPECCHIO CA cert to keystore
  java_cert:
    cert_path: "{{ specchio_client_ca_crt_file }}"
    cert_alias: "{{ specchio_client_ca_crt_alias }}"
    keystore_path: "{{ specchio_client_keystore_file }}"
    keystore_pass: "{{ specchio_client_keystore_password }}"
    state: present

- name: Create "Desktop" directory in SPECCHIO user home
  file:
    path: "{{ specchio_client_user_desktop_directory }}/"
    state: directory
    owner: specchio
    group: specchio

- name: Symlink SPECCHIO client to desktop
  template:
    src: specchio_client.desktop.j2
    dest: "{{specchio_client_desktop_link}}"
    owner: specchio
    group: specchio
    mode: 0711

- name: Create db_config.txt
  template:
    src: db_config.txt.j2
    dest: "{{specchio_client_db_config_file}}"
    owner: specchio
    group: specchio
    mode: 0700

# This is an ugly hack to autotrust the SPECCHIO desktop link.
# https://askubuntu.com/questions/1070057/trust-desktop-icons-without-clicking-them-manually-in-ubuntu-18-04-gnome-3
- name: Autotrust SPECCHIO desktop link on login
  blockinfile:
    path: "{{specchio_client_user_home_directory}}/.bash_profile"
    block: |
      if [[ -f "{{specchio_client_desktop_link}}" && $(gio info "{{specchio_client_desktop_link}}" | grep "metadata::trusted") == "" ]]; then
          gio set "{{specchio_client_desktop_link}}" "metadata::trusted" yes
          pkill nautilus
      fi
