---

#specchio_client_jar_path: "../../../../SPECCHIO/build/distributions/SPECCHIO-shadow-3.3.0.1.zip"
specchio_client_download_url: "https://github.com/ahueni/SPECCHIO/blob/SPECCHIO_Master/pkg/specchio-client.zip"
