---

specchio_client_download_url: "https://github.com/ahueni/SPECCHIO/blob/SPECCHIO_Master/pkg/specchio-client.zip?raw=true"
specchio_client_directory: /opt/specchio_client/
specchio_client_user_home_directory: "/home/specchio"
specchio_client_user_desktop_directory: "{{specchio_client_user_home_directory}}/Desktop/"
