---

# Download URL from where the SPECCHIO client zip will be downloaded.
specchio_client_download_url: "https://jenkins.specchio.ch/job/SPECCHIO/lastSuccessfulBuild/artifact/src/client/build/distributions/specchio-client.zip"

# Directory where the client should be extracted to
specchio_client_extraction_directory: "/opt/SPECCHIO"

# Destination directory where the SPECCHIO client was extracted
specchio_client_directory: "{{ specchio_client_extraction_directory }}/specchio-client"

# Destination of the db_config.txt file (containing login credentials)
specchio_client_db_config_file: "{{ specchio_client_directory }}/db_config.txt"

# Name of the SPECCHIO user.
specchio_client_user: "specchio"

# Path to SPECCHIO user home directory.
specchio_client_user_home_directory: "/home/{{ specchio_client_user }}"

# Path to the SPECCHIO user desktop directory.
specchio_client_user_desktop_directory: "{{specchio_client_user_home_directory}}/Desktop"

# Path to the SPECCHIO client desktop link.
specchio_client_desktop_link: "{{specchio_client_user_desktop_directory}}/SPECCHIO Java Client.desktop"

# Default credentials for the admin user
specchio_client_admin_password: "ALSOCHANGEME"
specchio_client_admin_user: "sdb_admin"

# Default connections information
specchio_client_connection_protocol: "https"
specchio_client_connection_server: "localhost"
specchio_client_connection_port: "8181"
specchio_client_connection_path: "/specchio_service"
specchio_client_connection_data_source: "jdbc/specchio"

# SPECCHIO CA certificates
specchio_client_ca_crt_file: "/tmp/specchio_ca.crt"
specchio_client_ca_crt_alias: "specchio_trust_ca"
specchio_client_keystore_file: "{{ specchio_client_directory }}/specchio.keystore"
specchio_client_keystore_password: "specchio"

# Directory with example database
specchio_client_dataset_directory: "{{specchio_client_user_desktop_directory}}/Example Data"
specchio_client_dataset_download_url: "https://specchio.ch/datasets/"
specchio_client_datasets:
  - SPECCHIO_20190320_125438_V3.34_TutorialData.sql.gz

# Base download path for the SPECCHIO guides
specchio_client_guide_download_url: "https://github.com/SPECCHIODB/Guides/raw/master"
specchio_client_guide_directory: "{{specchio_client_user_desktop_directory}}/Guides"
specchio_client_guides:
  - SPECCHIO_VM.pdf
  - SPECCHIO_ReleaseNotes.pdf
  - SPECCHIO_Tutorial.pdf
  - SPECCHIO_UserGuide.pdf
  - SPECCHIO_VMUpgradeGuide.pdf
