---

- hosts: all
  become: yes
  vars:
    - specchio_database_user_password: 'ALSOCHANGEME'
  roles:
    - role: glassfish4
    - role: mariadb
    - role: gnome
    - role: specchio_database
    - role: specchio_client
    - role: specchio_user
    - role: specchio_client
    - role: specchio_webapp
  tasks:
    - name: Install debugging and developments utils
      package:
        name: "{{ item }}"
        state: latest
      loop:
        - vim
        - curl
        - git
