---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    - specchio_database_password:           "ALSOCHANGEME"
    - specchio_webapp_database_password:    '{{ specchio_database_password }}'
    - specchio_client_admin_password:       '{{ specchio_database_password }}'

  pre_tasks:

    - import_tasks: ca_injection.yml

    - name: Set hostname
      hostname:
        name: specchio

    - name: Disable SELinux
      selinux:
        state: disabled

    - name: Update yum packages
      yum:
        name: '*'
        state: latest
        update_cache: yes

    - name: Install epel-release
      package:
        name: epel-release
        state: latest

    - name: Install yum-cron
      package:
        name: yum-cron
        state: latest

    - name: Enable automatic updates through yum-cron
      service:
        name: yum-cron
        state: started
        enabled: yes

    - name: Add SPECCHIO group
      group:
        name: specchio---

- name: Install OpenJDK
  package:
    name: java-1.8.0-openjdk-1.8.0.171-8.b10.el6_9
    #java_minor_version: 212
    #java_version: '8u212'
    #java_minor_version: 0.212
    #state: latest

- name: Install unzip
  package:
    name: unzip
    state: latest

- name: Create SPECCHIO client extraction directory
  file:
    path: "{{ specchio_client_extraction_directory }}"
    state: directory

- name: Download SPECCHIO client zip
  unarchive:
    src: "{{ specchio_client_download_url }}"
    dest: "{{ specchio_client_extraction_directory }}"
    remote_src: yes

- name: Add SPECCHIO CA cert to keystore
  java_cert:
    cert_path: "{{ specchio_client_ca_crt_file }}"
    cert_alias: "{{ specchio_client_ca_crt_alias }}"
    keystore_path: "{{ specchio_client_keystore_file }}"
    keystore_pass: "{{ specchio_client_keystore_password }}"
    state: present

- name: Create "Desktop" directory in SPECCHIO user home
  file:
    path: "{{ specchio_client_user_desktop_directory }}/"
    state: directory
    owner: specchio
    group: specchio

- name: Symlink SPECCHIO client to desktop
  template:
    src: specchio_client.desktop.j2
    dest: "{{ specchio_client_desktop_link }}"
    owner: specchio
    group: specchio
    mode: 0755

- name: Create db_config.txt
  template:
    src: db_config.txt.j2
    dest: "{{specchio_client_db_config_file}}"
    owner: specchio
    group: specchio
    mode: 0700
    
- name: Copy shell script to run client
  copy:
    src: run_specchio_client.sh
    dest: "{{specchio_client_shell_file}}"
    owner: specchio
    group: specchio
    mode: 0755    

- name: Ensure "Example Data" directory exists
  file:
    path: "{{ specchio_client_dataset_directory }}/"
    state: directory
    owner: specchio
    group: specchio

- name: Download example datasets to Desktop
  get_url:
    url: "{{ specchio_client_dataset_download_url }}/{{ item }}"
    dest: "{{ specchio_client_dataset_directory }}/"
  loop: "{{ specchio_client_datasets }}"

- name: Ensure "Guides" directory exists
  file:
    path: "{{ specchio_client_guide_directory }}/"
    state: directory
    owner: specchio
    group: specchio

- name: Download SPECCHIO guides
  get_url:
    url: "{{ specchio_client_guide_download_url }}/{{ item }}"
    dest: "{{ specchio_client_guide_directory }}/"
  loop: "{{ specchio_client_guides }}"

        state: present

    - name: Add SPECCHIO user
      user:
        name: specchio
        comment: SPECCHIO Spectral Information System
        home: /home/specchio
        group: specchio
        groups: wheel  # Add specchio user to sudo group
      ignore_errors: yes

    - name: Install GNOME desktop environment packages
      yum:
        name: "@^gnome-desktop-environment"
        state: latest

    - name: Install GNOME display manager package
      package:
        name: gdm
        state: latest

    - name: Set default target to "graphical"
      shell: systemctl set-default graphical.target

    - name: Change size of nautilus icons
      shell: dbus-launch gsettings set org.gnome.nautilus.icon-view default-zoom-level 'small'

    - name: Install MySQL workbench repository (for MySQL workbench)
      yum:
        name: https://dev.mysql.com/get/mysql80-community-release-el7-2.noarch.rpm
        state: present

    - name: Install MySQL workbench
      package:
        name: mysql-workbench
        state: latest

    - name: Install debugging and developments utils
      package:
        name: "{{ item }}"
        state: latest
      loop:
        - vim
        - curl
        - git

    # This is an ugly hack to autotrust the SPECCHIO desktop link.
    # https://askubuntu.com/questions/1070057/trust-desktop-icons-without-clicking-them-manually-in-ubuntu-18-04-gnome-3
    - name: Autotrust SPECCHIO desktop link on login
      blockinfile:
        path: "{{specchio_client_user_home_directory}}/.bash_profile"
        block: |
          if [ -z "$SSH_CLIENT" ] || [ -z "$SSH_TTY" ]; then
              declare -a LINKS=(
                  "/home/specchio/Desktop/SPECCHIO Java Client.desktop"
                  "/home/specchio/Desktop/SPECCHIO Backup Tool.desktop"
                  "/home/specchio/Desktop/SPECCHIO Update Tool.desktop"
              )

              TRIGGER_RELOAD=0

              for LINK in "${LINKS[@]}"; do
                  if [[ -f "${LINK}" && $(gio info "${LINK}" | grep "metadata::trusted") == "" ]]; then
                      echo "Trust ${LINK}"
                      gio set "${LINK}" "metadata::trusted" yes
                      TRIGGER_RELOAD=1
                  fi
              done

              if [[ $TRIGGER_RELOAD -eq 1 ]]; then
                    pkill nautilus
              fi
          fi

  roles:
    - role: specchio_update_tool
    - role: specchio_backup_tool
    - role: specchio_client
    - role: specchio_webapp
  
  post_tasks:
    - name: Cleanup sensitive files
      file:
        name: "{{ item }}"
        state: absent
      loop:
        - /tmp/specchio_ca.p12
        - /tmp/specchio_ca.crt
