---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    # TODO: Extract into Jenkins credentials
    - specchio_database_password:           'ALSOCHANGEME'
    - specchio_webapp_database_password:    '{{ specchio_database_password }}'
    - specchio_database_user_password:      '{{ specchio_database_password }}'
    - specchio_client_admin_password:       '{{ specchio_database_password }}'

  pre_tasks:
    - name: Update yum packages
      yum:
        name: '*'
        state: latest
        update_cache: yes

    - name: Install epel-release
      package:
        name: epel-release
        state: latest

    - name: Install GNOME desktop environment packages
      yum:
        name: "@^gnome-desktop-environment"
        state: latest

    - name: Install GNOME display manager package
      package:
        name: gdm
        state: latest

    - name: Set default target to "graphical"
      shell: systemctl set-default graphical.target

    - name: Install mariadb package
      package:
        name: mariadb-server
        state: latest

    - name: Enable mariadb service
      service:
        name: mariadb
        state: started
        enabled: yes

  roles:
    - role: specchio_database
    - role: specchio_user
    - role: specchio_client
    - role: specchio_webapp

  post_tasks:
    - name: Install debugging and developments utils
      package:
        name: "{{ item }}"
        state: latest
      loop:
        - vim
        - curl
        - git
