---

- hosts: all
  become: yes
  roles:
    - role: glassfish
    - role: mariadb
    - role: gnome
    - role: specchio_user
    - role: specchio_client
    - role: specchio_webapp
  tasks:
    - name: Install debugging and developments utils
      package:
        name: "{{ item }}"
        state: latest
      loop:
        - vim
        - curl
        - git
