---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    - specchio_database_user_password: 'ALSOCHANGEME'
    - specchio_client_admin_password: '{{ specchio_database_user_password }}'

  pre_tasks:
    - name: Update yum packages
      yum:
        name: '*'
        state: latest
        update_cache: yes
    - name: Install epel-release
      package:
        name: epel-release
        state: latest

  roles:
    - role: mariadb
    - role: gnome
    - role: specchio_database
    - role: specchio_user
    - role: specchio_client
    - role: specchio_webapp

  post_tasks:
    - name: Install debugging and developments utils
      package:
        name: "{{ item }}"
        state: latest
      loop:
        - vim
        - curl
        - git
