---

# The mariadb-server version in the official CentOS repository was to old to
# import the database of the "old" virtual machine image (which used MySQL 5.6).
- name: Install official mariadb repositories
  yum_repository:
    name: mariadb
    description: MariaDB yum repository
    baseurl: http://yum.mariadb.org/10.3/centos7-amd64
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: yes


- name: Install mariadb package
  package:
    name: MariaDB-server
    state: latest

- name: Enable mariadb service
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Install python mysql library
  package:
    name: MySQL-python
    state: latest

# We only want to run the SQL scripts if the database does not exist yet.

- name: check if DB exists
  shell: mysql -e 'SHOW DATABASES;' | grep 'specchio'
  register: dbstatus
  failed_when: dbstatus.rc == 2

- name: Import SPECCHIO database schema
  mysql_db:
    name: all
    state: import
    target: "{{ specchio_webapp_sql_directory }}/SPECCHIO_V3.3.4.sql"
  when: dbstatus.rc == 1

# Instead of using the mysql_user module to manage the database users, we use the existing SQL
# scripts. Those might change in the future. This way we will always be up to date.

- name: Replace sdb_admin password in SQL Script
  replace:
    path: "{{ specchio_webapp_sql_directory }}/sdb_admin_creation.sql"
    regexp: '(.*)sdb_admin_password(.*)$'
    replace: '\1{{ specchio_webapp_database_password }}\2'
    backup: yes
  when: dbstatus.rc == 1

- name: Create SPECCHIO database user
  mysql_db:
    name: all
    state: import
    target: "{{ specchio_webapp_sql_directory }}/sdb_admin_creation.sql"
  when: dbstatus.rc == 1
