---

- include: database.yml
- include: glassfish.yml
- include: java_mysql_connector.yml
- include: specchio_webapp.yml
- include: tls_setup.yml

- name: Deploy webapp.war to glassfish
  command: "{{ specchio_webapp_glassfish_asadmin_file }} deploy --force {{ specchio_webapp_war }}"
