---

- name: Create SPECCHIO webapp install directory
  file:
    path: "{{ specchio_webapp_directory }}"
    state: directory

- name: Download SPECCHIO client zip
  unarchive:
    src: "{{ specchio_webapp_download_url }}"
    dest: "{{ specchio_webapp_directory }}"
    remote_src: yes
