---

- name: Create SPECCHIO webapp install directory
  file:
    path: "{{ specchio_webapp_directory }}"
    state: directory

- name: Download SPECCHIO webapp war
  get_url:
    url: "{{ specchio_webapp_download_url }}"
    dest: "{{ specchio_webapp_directory }}"
