---

- name: Install zenity
  package:
    name: zenity
    state: latest

- name: Create "Desktop" directory in SPECCHIO user home
  file:
    path: /home/specchio/Desktop
    state: directory
    owner: specchio
    group: specchio

- name: Create link on desktop
  copy:
    src: specchio_backup_tool.sh
    dest: /usr/local/bin/

- name: Create link on desktop
  copy:
    src: specchio_backup_tool.desktop
    dest: "/home/specchio/Desktop/SPECCHIO Backup Tool"
